### ISSUE TITLE
Mugshot sizes out of bounds

### ISSUE THREAD

**Issue by bleehu** [bleehu/CXDocs#244]
bestiary pictures all have a class called "mugshot" that used to have a size constraint on them. 

Large pictures uploaded to the bestiary are jumping off of their cards. i.e. https://compoundx.org/monster#Shockraypanel
Could we get a quick patch in the next deploy?

**Comment by RyuGuardian** [comment]
This is a one-line fix if you just want to make sure the images don't overflow their parent, so I'm tempted to just include the change with another PR that edits styles (it'd be a constraint on the <img> tag that'd be a good edit for overall styling). I'd rather not do more than that since the styling for the bestiary is going to be overhauled later anyway.

(Having large images increases load times as well, so usually display images should be limited in size. If you want larger images available, there can be links to them or downloadable files (a concern for way down the line, obviously).)

**Comment by RyuGuardian** [comment]
Addressed with PR #252
